# Generated by Django 6.0.5 on 2026-05-26 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='登录账号，字母开头，可包含字母/数字/下划线', max_length=150, unique=True, verbose_name='用户名')),
                ('role', models.CharField(choices=[('ADMIN', '教学管理员'), ('TEACHER', '教学人员'), ('PRINCIPAL', '校长')], default='ADMIN', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, help_text='禁用后无法登录系统', verbose_name='是否启用')),
                ('is_staff', models.BooleanField(default=False, help_text='设为 True 才能登录 Django Admin 后台', verbose_name='是否可登录 Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='用户所属组，组权限会自动继承', related_name='accounts_user_set', related_query_name='accounts_user', to='auth.group', verbose_name='用户组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='用户的独立权限', related_name='accounts_user_set', related_query_name='accounts_user', to='auth.permission', verbose_name='用户权限')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
