# Generated by Django 6.0.5 on 2026-05-26 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('level', models.IntegerField(help_text='1=省/直辖市/自治区，2=地级市/自治州，3=区/县/县级市', verbose_name='行政级别')),
                ('code', models.CharField(help_text='GB/T 2260 六位数字代码', max_length=20, unique=True, verbose_name='行政区划代码')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='persons.region', verbose_name='上级行政区划')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'db_table': 'regions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_card', models.CharField(db_index=True, help_text='15位（旧版）或18位（新版），系统唯一标识', max_length=18, unique=True, verbose_name='身份证号')),
                ('gender', models.CharField(blank=True, help_text='可从身份证号自动提取，也可手动修改', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, help_text='可从身份证号自动提取', null=True, verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, help_text='不做唯一约束——允许父母子女共用同一号码', max_length=20, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='电子邮箱')),
                ('address_detail', models.CharField(blank=True, help_text='门牌号/街道等具体地址', max_length=200, verbose_name='详细地址')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系人电话')),
                ('openid', models.CharField(blank=True, help_text='微信小程序登录标识，为空表示未绑定微信', max_length=100, null=True, unique=True, verbose_name='微信 OpenID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_city', to='persons.region', verbose_name='市')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_district', to='persons.region', verbose_name='区')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_province', to='persons.region', verbose_name='省')),
            ],
            options={
                'verbose_name': '人员档案',
                'verbose_name_plural': '人员档案',
                'db_table': 'persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['parent', 'level'], name='idx_region_parent_level'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['phone'], name='idx_person_phone'),
        ),
    ]
