# Generated by Django 6.0.5 on 2026-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(help_text='GB/T 2260 六位数字代码', max_length=20, verbose_name='行政区划代码'),
        ),
    ]
