# Generated by Django 6.0.5 on 2026-05-27 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：驾驶岗位、轮机岗位', max_length=50, verbose_name='岗位名称')),
                ('code', models.CharField(help_text='如：DRIVING、ENGINE', max_length=20, unique=True, verbose_name='岗位编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '培训岗位',
                'verbose_name_plural': '培训岗位',
                'db_table': 'posts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ClassStatusRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30, verbose_name='源状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='目标状态')),
                ('allowed_role', models.CharField(choices=[('ADMIN', '教学管理员'), ('TEACHER', '教学人员'), ('PRINCIPAL', '校长'), ('SYSTEM', '系统自动')], max_length=20, verbose_name='允许触发的角色')),
                ('precondition', models.CharField(choices=[('NONE', '无前置条件'), ('MIN_ENROLLMENT_1', '至少1名已报名学员'), ('LOG_SUBMIT_TIME', '必须记录递交时间'), ('STATS_COMPLETED', '必须完成出勤统计'), ('ALL_COURSES_DONE', '所有课程已结束')], default='NONE', help_text='枚举常量，通过 match 分支在 Service 层求值', max_length=30, verbose_name='前置条件')),
                ('is_reversible', models.BooleanField(default=False, help_text='True=允许从 to_status 回到 from_status', verbose_name='允许逆向')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '状态转换规则',
                'verbose_name_plural': '状态转换规则',
                'db_table': 'class_status_rules',
                'ordering': ['from_status', 'to_status'],
                'constraints': [models.UniqueConstraint(fields=('from_status', 'to_status'), name='uq_transition_rule')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：一类船长、二类驾驶员', max_length=50, verbose_name='职务名称')),
                ('code', models.CharField(help_text='如：CAPTAIN_1、DRIVER_2', max_length=20, unique=True, verbose_name='职务编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(help_text='多对一：多个职务属于同一岗位', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='training.post', verbose_name='所属岗位')),
            ],
            options={
                'verbose_name': '培训职务',
                'verbose_name_plural': '培训职务',
                'db_table': 'positions',
                'ordering': ['post__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：2026年第一期驾驶一类培训班', max_length=200, unique=True, verbose_name='班级名称')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ENROLLING', '报名中'), ('ROSTER_GENERATED', '名册已生成'), ('SUBMITTED', '已递交'), ('PENDING_APPROVAL', '待审批'), ('APPROVED', '已审批'), ('IN_PROGRESS', '进行中'), ('FINISHED', '已结束'), ('ARCHIVED', '已归档')], db_index=True, default='DRAFT', max_length=30, verbose_name='班级状态')),
                ('expected_start_date', models.DateField(help_text='创建班级时填写的计划开班日', verbose_name='预计开班日期')),
                ('actual_start_date', models.DateField(blank=True, help_text='状态切换至 IN_PROGRESS 时自动填充', null=True, verbose_name='实际开班日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('position', models.ForeignKey(help_text='引用 Position 表，如一类船长、二类驾驶员', on_delete=django.db.models.deletion.PROTECT, related_name='training_classes', to='training.position', verbose_name='培训职务')),
            ],
            options={
                'verbose_name': '培训班级',
                'verbose_name_plural': '培训班级',
                'db_table': 'training_classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='如：船舶操纵、航海英语', max_length=200, verbose_name='课程名称')),
                ('course_type', models.CharField(choices=[('theory', '理论课'), ('practical', '实操课')], max_length=20, verbose_name='课程类型')),
                ('schedule_date', models.DateField(verbose_name='上课日期')),
                ('time_slot', models.CharField(choices=[('morning', '上午'), ('afternoon', '下午')], max_length=20, verbose_name='时段')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='上课地点')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='training.trainingclass', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '课程安排',
                'verbose_name_plural': '课程安排',
                'db_table': 'course_schedules',
                'ordering': ['schedule_date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='ClassStatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='目标状态')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('remark', models.TextField(blank=True, help_text='如：逆向转换的原因说明', verbose_name='备注')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='training.trainingclass', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '状态变更日志',
                'verbose_name_plural': '状态变更日志',
                'db_table': 'class_status_transitions',
                'ordering': ['-operated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingclass',
            index=models.Index(fields=['status', 'expected_start_date'], name='idx_class_status_date'),
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.UniqueConstraint(fields=('training_class', 'schedule_date', 'time_slot'), name='uq_class_date_slot'),
        ),
    ]
