# Generated by Django 6.0.5 on 2026-05-28 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_region_code'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='Django-Q 任务 ID', max_length=255, verbose_name='任务ID')),
                ('row_num', models.IntegerField(help_text='Excel 中的行号（从2开始，第1行为表头）', verbose_name='行号')),
                ('error_type', models.CharField(help_text='如：ID_CARD_FORMAT / DUPLICATE / PERSON_CREATE_FAIL', max_length=50, verbose_name='错误类型')),
                ('error_message', models.TextField(verbose_name='错误消息')),
                ('raw_data', models.JSONField(default=dict, help_text='该行的原始 Excel 数据（JSON）', verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '导入错误日志',
                'verbose_name_plural': '导入错误日志',
                'db_table': 'import_error_logs',
                'ordering': ['task_id', 'row_num'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(choices=[('ENROLLED', '已报名'), ('CHECKED_IN', '已报到'), ('WITHDRAWN', '已退学')], default='ENROLLED', max_length=20, verbose_name='报名状态')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='报到确认时自动填充', null=True, verbose_name='报到时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='persons.person', verbose_name='学员档案')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.trainingclass', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学员报名',
                'verbose_name_plural': '学员报名',
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('person', 'training_class'), name='uq_person_class')],
            },
        ),
    ]
