# Generated by Django 6.0.5 on 2026-05-31 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='考勤日期')),
                ('time_slot', models.CharField(choices=[('morning', '上午'), ('afternoon', '下午')], max_length=10, verbose_name='时段')),
                ('status', models.CharField(choices=[('present', '出勤'), ('absent', '缺勤'), ('leave', '请假')], default='present', max_length=10, verbose_name='考勤状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('enrollment', models.ForeignKey(help_text='关联报名记录（而非 Person），一人多班级时考勤独立', on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment', verbose_name='报名记录')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingclass', verbose_name='培训班级')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'db_table': 'attendance_records',
                'indexes': [models.Index(fields=['training_class', 'record_date'], name='idx_attendance_class_date')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'training_class', 'record_date', 'time_slot'), name='uq_attendance_enrollment_date_slot')],
            },
        ),
    ]
